##  Ren's zshrc options
##  These can be linked to your .zshrc with a line like: . "$HOME/Documents/dots/zshrc"
##  	in your .zshrc, linking to wherever you have this file stored. Or you can just
##		copy these lines directly to your .zshrc, i wont stop you

# Options, binds and aliases

autoload -U colors && colors
PS1="[%{$fg[red]%}%n%{$reset_color%}@%{$fg[blue]%}%m %{$fg[yellow]%}%~%{$reset_color%}]# "

setopt histignoredups

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^[[Z' reverse-menu-complete

alias fetch="clear && fastfetch"
alias song-download="yt-dlp -f 'ba' -x --audio-format mp3"
alias vim="nvim"
alias v="nvim"
alias ls="eza -h"
alias cat="bat"
alias clear="echo -n \"\e[H\e[3J\""
alias cls="clear"
alias search-history="cat ~/.zsh_history | grep"
alias preview-media="ffplay -autoexit -vf scale=-1:800"

export EDITOR="nvim"

fastfetch --config $HOME/.config/fastfetch/startup.jsonc
